services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_IMAGE_TAG:-16.11.10-ce.0}
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.club012.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.club012.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
    ports:
      - '80:80'
      - '443:443'
      # - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'