services:
  openldap:
    # image: osixia/openldap:1.1.7
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION="Club012 Com"
      - LDAP_DOMAIN="club012.com"
      - LDAP_ADMIN_PASSWORD="${LDAP_ADMIN_PASSWORD:-admin}"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-conf:/etc/ldap/slapd.d 
    ports:
      - 389:389

volumes:
  ldap-data:
  ldap-conf:

