# https://github.com/osixia/container-openldap/blob/develop/README.md#-environment-variables
services:
  openldap:
    image: osixia/openldap
    container_name: openldap
    restart: unless-stopped
    volumes:
      - openldap-conf:/etc/openldap/slapd.d
      - openldap-data:/var/lib/openldap/openldap-data
      - openldap-backups:/var/lib/openldap/openldap-backups
    ports:
      - "389:3890"
      - "636:6360"
    environment:
      OPENLDAP_BOOTSTRAP_ORGANIZATION: "Club012 Com"
      OPENLDAP_BOOTSTRAP_SUFFIX: "dc=club012,dc=com"

volumes:
  openldap-conf:
  openldap-data:
  openldap-backups:
