services:
  vault:
    image: hashicorp/vault:2.0
    container_name: vault-server
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - vault_data:/vault/data
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: vault server -config=/vault/config/vault.hcl

volumes:
  vault_data:
