services:
 postgres:
   image: postgres:16
   container_name: keycloak_postgres
   volumes:
     - postgres_data:/var/lib/postgresql/data
   environment:
     POSTGRES_DB: ${POSTGRES_DB:-keycloak}
     POSTGRES_USER: ${POSTGRES_USER:-keycloak}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   restart: unless-stopped

 keycloak:
   image: quay.io/keycloak/keycloak:26.7.0
   container_name: keycloak
   command: start
   environment:
     KC_PROXY_HEADERS: xforwarded
     KC_HTTP_ENABLED: true
     KC_PROXY: edge
     KC_HOSTNAME_STRICT: false
     KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
     KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
     KC_DB: postgres
     KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
     KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
     KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - 8080:8080
   restart: unless-stopped
   depends_on:
     - postgres
